// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psfvdenzdudcxmxwjapx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzZnZkZW56ZHVkY3hteHdqYXB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MjE2OTAsImV4cCI6MjA3MTI5NzY5MH0.7BPqBf7VCEkPfOroW49X6YZGdU1h2fGab8yiNjIBAQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});